# Generated by Django 5.1.1 on 2024-09-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizGroup',
        ),
    ]
