# Generated by Django 5.1.1 on 2024-09-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='firstname',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='surname',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
