# Generated by Django 5.1.1 on 2024-09-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0014_usergroup_firstname_usergroup_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
    ]
