# Generated by Django 5.1.1 on 2024-09-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0015_remove_usergroup_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='group',
            new_name='answer',
        ),
    ]
