# Generated by Django 5.1.1 on 2024-09-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0016_rename_group_usergroup_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('firstname', models.CharField(blank=True, max_length=55, null=True)),
                ('surname', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='answer',
            new_name='group',
        ),
    ]
